// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	clusternetworkpolicyv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/clusternetworkpolicy/v1"
	versioned "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/clusternetworkpolicy/v1/apis/clientset/versioned"
	internalinterfaces "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/clusternetworkpolicy/v1/apis/informers/externalversions/internalinterfaces"
	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/clusternetworkpolicy/v1/apis/listers/clusternetworkpolicy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterNetworkPolicyInformer provides access to a shared informer and lister for
// ClusterNetworkPolicies.
type ClusterNetworkPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClusterNetworkPolicyLister
}

type clusterNetworkPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterNetworkPolicyInformer constructs a new informer for ClusterNetworkPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterNetworkPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterNetworkPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterNetworkPolicyInformer constructs a new informer for ClusterNetworkPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterNetworkPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().ClusterNetworkPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().ClusterNetworkPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&clusternetworkpolicyv1.ClusterNetworkPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterNetworkPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterNetworkPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterNetworkPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusternetworkpolicyv1.ClusterNetworkPolicy{}, f.defaultInformer)
}

func (f *clusterNetworkPolicyInformer) Lister() v1.ClusterNetworkPolicyLister {
	return v1.NewClusterNetworkPolicyLister(f.Informer().GetIndexer())
}
