// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterNetworkPolicyListerExpansion allows custom methods to be added to
// ClusterNetworkPolicyLister.
type ClusterNetworkPolicyListerExpansion interface{}

// ClusterNetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// ClusterNetworkPolicyNamespaceLister.
type ClusterNetworkPolicyNamespaceListerExpansion interface{}
